### ISSUE TITLE
Blade directive for SAMLRequest input field not working as is

### ISSUE THREAD

**Issue by upwebdesign** [codegreencreative/laravel-samlidp#1]
In the `SamlIdpServiceProvider` there is an issue with the Blade directive when loading the login page with a SAMLRequest. It's just not working. I found an example that may lead us in the right direction.

https://github.com/spatie/laravel-honeypot/blob/master/src/HoneypotServiceProvider.php

**Comment by gmartinez** [comment]
Hi there, I am having this same issue, the blade directive is not doing anything...although the problem seems to have been taken care of. Any guidance on what I might have done wrong is appreciated.

**Comment by upwebdesign** [comment]
It would seem that the `SAMLRequest` query parameter is not in the URL if the blade directive is not printing a hidden input field.

```php
            if (request()->filled('SAMLRequest')) {
                return "<?php echo view('samlidp::components.input'); ?>";
            }
```

You could try to add that query parameter manually to the login URL and see if the directive is working for you.

**Comment by gmartinez** [comment]
@upwebdesign thanks for the prompt response, indeed that was the issue, sorry I am new to SSO/SAML.

If you do not mind I have a couple more generic questions.

My scenario is the following, when my users are logged in my app they need to click on a link that will take them to a third party app which needs to SSO to my app.

I think I've configured everything there is to, but I am lost in the flow I guess. I'd expect to be able to define a route in my app that initiates the process of the third party app to sso against mine and then redirect the user to its service. Am I way off ?

**Comment by upwebdesign** [comment]
@gmartinez I found SSO with SAML extremely confusing. This package aims to ease the pain. Assuming you have followed the README.md of this package, you should be very close to implementing SSO with SAML. Normally I would not answer unrelated questions to the issue, but... The service provider (third party app) needs to have an initiating URL, so you are correct there. Assuming they are sending the SAMLRequest parameter, an assertion should be created and sent to the service provider allowing your user to log into their service. That is about all I can provide for now. @agmadt let us know if you have any comments on this.

**Comment by gmartinez** [comment]
@upwebdesign final message to provide some input/closure in order to correspond your kind prompt replies to my questions and maybe also help some other "lost soul" that at some point find itself in such dire straits :)

Basically, we could make it work, and as you indicated we were quite close.

We implemented a route that uses a samlrequest xml string, and redirect to our login controller (which has the package's blade directive in place) passing the SAMLRequest parameter and....voilà

Thanks for your work !

**Comment by blorange2** [comment]
@gmartinez I know for you this would have been a while ago but your solutions seems sensible. Did you literally just send your own application what you would normally expect to receive from a Service Provider?

Thank you in advance.
