### ISSUE TITLE
Jetstream user delete account resulting in redirect error

### ISSUE THREAD

**Issue by ChadwickLloyd** [codegreencreative/laravel-samlidp#103]
Hi,

Im using laravel 8 with jetstream, and while doing testing have come across an issue.

The user is successfully deleted, however when saml logout is called an error occurs.

I am being displayed this issue:

ErrorException
Object of class Livewire\Redirector could not be converted to int

which is starting here (vendor/codegreencreative/laravel-samlidp/src/Listeners/SamlLogout.php):

`public function handle(Logout $event)

    {

        // Make sure we are not in the process of SLO when handling the redirect

        if (in_array($event->guard, config('samlidp.guards')) && null === session('saml.slo')) {

            abort(redirect('saml/logout'), 200);

        }

    }`

Im not entirely sure, but I believe its because the call parameters arent aligned.

It should be:
`app()->abort($code, $message, $headers);`

Has anyone come across a similar issue / have any suggestions for resolving this?

Cheers.

**Comment by upwebdesign** [comment]
@ChadwickLloyd did you ever figure this out? I don't belive the abort helper parameters are reversed.
