### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by dev-tejal** [codegreencreative/laravel-samlidp#104]
I am using laravel 5.8 for single signin from zoom(SP). But I am getting above error when SAML request come to my laravel server.

**Comment by upwebdesign** [comment]
@dev-tejal, sorry, I never heard of such a thing. However, it sounds like you have a key issue. Maybe a public key is being used where a private key should be?

**Comment by dev-tejal** [comment]
Here Key is generated using command which is mentioned in doc.

**Comment by upwebdesign** [comment]
@dev-tejal, check to make sure Zoom requires signed requests.

**Comment by dev-tejal** [comment]
Thank you for support @upwebdesign .
It is resolved. It was permission error of key.pem file
