### ISSUE TITLE
SingleLogoutService in metadata

### ISSUE THREAD

**Issue by russclewett-mw** [codegreencreative/laravel-samlidp#114]
Hi there!

I've got your package set up for SSO with a Craft CMS site and am using a plugin that implements an SP.  SSO is working fine but logout is breaking on the Craft side.  When I raised this with the plugin developer they say we need "SingleLogoutService" in our Metadata (https://github.com/flipboxfactory/saml-sp/issues/191#issuecomment-1494970796).  

Is this something we can add ourselves or is in not possible.

Thanks

**Comment by upwebdesign** [comment]
@russclewett-mw, you don't need to use the supplied metadata XML view. Instead, you can use your own if you like.

**Comment by russclewett-mw** [comment]
Ahh yes of course!  However I'm not sure what the Location and ResponseLocation for the node would be.
