### ISSUE TITLE
dispatchNow() deprecated in Laravel 10

### ISSUE THREAD

**Issue by will-dive** [codegreencreative/laravel-samlidp#115]
On line 35 of the LogoutController you have the code `return redirect(SamlSlo::dispatchNow($sp))`. However `dispatchNow()` has been deprecated in Laravel 10.

Suggestion: replace `dispatchNow` with `dispatchSync()`.

**Comment by upwebdesign** [comment]
@will-dive, excellent catch. I will update.

**Comment by will-dive** [comment]
Thanks

**Comment by upwebdesign** [comment]
@will-dive, I created a new release with this update.
