### ISSUE TITLE
SSO Access

### ISSUE THREAD

**Issue by rwnabdevs** [codegreencreative/laravel-samlidp#116]
Dear Jesse,

I want to implement SSO, so when user login to my portal should be able to access the courses on another portal of my client.
I have setup the IDP and sent the meta data xml to the client (who is a service provider to courses). 
My client sent me the ACS url and his meta data url.
 
I have placed all the Service Provider details along with certificate in the config file (samlidp.php).
But my client technical team says as below:

_" I can log into your system, but I don't see any calls to ACS URL from there. I'm only getting redirected to the course page. Could you please verify if you're downloading the metadata from https://xxx.xxx.xxx/auth/saml/metadata.xml and using "My Portal" as the Destination Resource (or RelayState)?"_

Can you please let me know what could be the issue for not calling the client ACS url. Not sure how to debug it.

Regards,
NB

**Comment by upwebdesign** [comment]
@rwnabdevs, although you explained the issue reasonably well, there is no way to determine what is going wrong on your end. It could be on their end. With that said, I can only do so much to help you with the current information. The SAML config file has something wrong, but this is a total guess. Have you been able to sniff the SAML HTTP redirects to see what is happening?

**Comment by upwebdesign** [comment]
@rwnabdevs, I would pay close attention to the documentation. Make sure you have followed every piece of instruction. If it is true that your login page is redirecting with the SAMLRequest and RelayState, then the SP should be able to read it.

**Comment by upwebdesign** [comment]
@rwnabdevs, what version of Laravel are you using?

**Comment by upwebdesign** [comment]
@rwnabdevs, what version of this package are you using? For your version of Laravel, it looks like you should be using `^1.0`.
