### ISSUE TITLE
SP initiated login results in HTTP 500

### ISSUE THREAD

**Issue by ockstadt** [codegreencreative/laravel-samlidp#120]
Hi,
when you committed [Intricate changes](https://github.com/codegreencreative/laravel-samlidp/commit/1ab6d6ec8a90b13a1a53151259ce021f31b9d3f9#diff-fd92e984182d137f92a3b9660523fd285aa621e4390fe5de80b1b860f49ccf8cL22) you possibly introduced a bug a when using the "redirect" resp. "response" in combination with Laravel's helper function [abort](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/helpers.php#L37). The status code is not set for the response but as second argument for the "abort" and thus will not be recognized because the first argument is of type [Symfony\Component\HttpFoundation\Response](https://github.com/symfony/http-foundation/blob/6.3/Response.php).

Besides of that, the helper function throws an [Illuminate\Http\Exceptions\HttpResponseException](https://github.com/laravel/framework/blob/master/src/Illuminate/Http/Exceptions/HttpResponseException.php) which is not an HttpException and thus will throw a 500 instead of the status code you set for the response ([Handler.php](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L600)).

You copied this possible bug to https://github.com/codegreencreative/laravel-samlidp/blob/master/src/Listeners/SamlLogin.php#L23.

This 500 causes an issue when you initiate the login process from the service provider and you are not logged in in your identity provider.

Can you please confirm that my assumption is right? Maybe you can provide a fix on short term?

Thank you in advance

Best regards

**Comment by upwebdesign** [comment]
@ockstadt it sounds like you have a good grasp of the issue, could you attempt a PR to fix the issue, and I will take a look? I assume you believe it should be like this:

```php
// Update
abort(response(SamlSso::dispatchNow()), 302);
// To
abort(response(SamlSso::dispatchNow(), 302));
```

**Comment by ockstadt** [comment]
Hi @upwebdesign ,
thank you for your fast reply!

Exactly, this change should at least set the correct HTTP status code for the Response used as first argument of "abort". But later in the process the HttpResponseException thrown by "abort" still causes a 500.

Your intention was to abort the processing and send a Response with status code 302, right? Then "abort" will not work because Illuminate\Http\Exceptions\HttpResponseException does not implement the interface Symfony\Component\HttpKernel\Exception\HttpExceptionInterface, but this is not under control of your package. Maybe throwing a Symfony\Component\HttpKernel\Exception\HttpException instead will solve the issue. Il will give i a try and create a PR if works.

**Comment by ockstadt** [comment]
Good morning,
I created two PRs, somehow it did not work to put the changes in one PR..

I could not yet figure out why abort(redirect()) and abort(back()) are working as expected but your code results in an HTTP 500...

**Comment by ockstadt** [comment]
Good morning,

the strange behaviour I am experiencing with the HTTP 500 is caused by [ProtoneMedia\Splade\SpladeCore](https://github.com/protonemedia/laravel-splade/blob/main/src/SpladeCore.php#L351) where the response of the HttpResponseException is transformed into a valid response which then causes the [exception handler](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Exceptions/Handler.php#L402) to return the new response instead of the original response.

I had to write my own exception handler to add some additional logic for my usecase and then ran into the next issue with splade but this is not related to your package.

It would be great if you merged the PRs so I can get rid of my temporary solution which I cannot check in.

Thanks in advance!

Best regards

**Comment by upwebdesign** [comment]
@ockstadt I've merged your PR and created a bug-fix release.
