### ISSUE TITLE
Get error log when logout

### ISSUE THREAD

**Issue by viet-nguyen-1926** [codegreencreative/laravel-samlidp#126]
Hi,
I have a question.
My SP is nextcloud and laravel app
 when i logout from  laravel app i get 405 error.
when Saml idp send a request to nextcloud server with OPTIONS method it happens
Have you get this error like this?
Can i change this method to GET ?

![image](https://github.com/codegreencreative/laravel-samlidp/assets/68979783/e603b764-7479-48fe-93e7-f8aebd1ff397)
![image](https://github.com/codegreencreative/laravel-samlidp/assets/68979783/36642ad5-ddba-4607-afda-943e541699de)

**Comment by upwebdesign** [comment]
@viet-nguyen-1926, this is a CORS issue. You will need to research CORS and how to fix the problem. Since I cannot see the domain names, I cannot give any additional information.
