### ISSUE TITLE
how to redirect after Fortify two-factor

### ISSUE THREAD

**Issue by ashrafbendary** [codegreencreative/laravel-samlidp#129]
I am using the package to provide saml idp login to clients 
but when I use the package with jetstream login it work normally but when activate 2fa its redirect to the application home page not to the sp client 

laravel 10.x

**Comment by upwebdesign** [comment]
@ashrafbendary, unfortunately, I have not used this package with Jetstream/2fa. Perhaps you find someone who has by posting in the [discussions](https://github.com/codegreencreative/laravel-samlidp/discussions).
