### ISSUE TITLE
Logout leaves the user logged into the IDP

### ISSUE THREAD

**Issue by zanderwar** [codegreencreative/laravel-samlidp#13]
When logging out, the request is broadcasted to all SP's fine, but you remain logged in to the IDP, so when the SP returns you to log in, you're still logged in despite logging out.

This may not be a bug, but didn't feel semantically correct.

**Comment by upwebdesign** [comment]
@zanderwar Simply logout your users as you would normally, `POST` to `/logout` or what ever route you are using. There is an event listener on `Illuminate\Auth\Events\Logout` to handle SLO.

**Comment by zanderwar** [comment]
Perfect, thanks
