### ISSUE TITLE
Accessing login page invalidates session

### ISSUE THREAD

**Issue by TanguyHefnaoui** [codegreencreative/laravel-samlidp#131]
I am using this library to authenticate users before they access our product's documentation (behind sso auth).
I want to make it so if our users are already logged in (which will be in most cases) the sso authentication happens automatically. However I am running into some issues, when accessing the login page from the service provider auth request, the users are always logged out (session seems to be invalidated when accessing the page). Any idea what could be causing this?

I am running laravel 10 with a vue front end

**Comment by upwebdesign** [comment]
@TanguyHefnaoui, I would recommend moving this to a discussion rather than an issue. From what I am reading, it is not an issue with the package but possibly an implementation issue.
