### ISSUE TITLE
jobs/SamlSlo.php class not found error

### ISSUE THREAD

**Issue by vuekev** [codegreencreative/laravel-samlidp#16]
Hi,

Great package, and hoping to integrate it into our SSO solution. However, I'm running into a problem with single-log-off, initiated from service provider. An incoming logout request seems to cause SamlSlo.php to blow up with a class not found error -
Class 'CodeGreenCreative\SamlIdp\Jobs\DeserializationContext' not found
If I add - use LightSaml\Model\Context\DeserializationContext;
to the beginning of the file, it works.
Using Laravel 5.8.35. If you need any more detail, please let me know.
Thanks,
Kevin.

**Comment by upwebdesign** [comment]
I too am getting this error. @agmadt could you take a look and see if you can spot the issue?

**Comment by upwebdesign** [comment]
@vuekev I have added a fix and a new release if you want the latest code. @agmadt no worries about working on this.

**Comment by vuekev** [comment]
Thanks for the update, that's great!
