### ISSUE TITLE
Make command for creating certificate files

### ISSUE THREAD

**Issue by upwebdesign** [codegreencreative/laravel-samlidp#2]
Use the following command to create new certificate and private key for yoru IdP.

```shell
php artisan samlidp:cert --days 7300 --keyname key.pem --certname cert.pem
```

--days <int>
    Number of days to add from today as the expiration date
    Default: 7300

--keyname <string>
    Full name of the certificate key file
    Default: key.pem

--certname <string>
    Full name to the certificate file
    Default: cert.pem

This command will do something similar to the following

```shell
cd storage/samlidp
openssl req -x509 -sha256 -nodes -days 7300 -newkey rsa:2048 -keyout key.pem -out cert.pem
```

**Comment by upwebdesign** [comment]
@agmadt To extend this a little further, let's check to see if files exist already for the chosen key and cert name. If the files exist, let's prompt the user if they would like to overwrite the old cert and key.

prompt: `The name chosen for the certificate and key already exist, would you like to overwrite the existing certificate and key? y/[n]`

**Comment by mandersondesign** [comment]
Are you guys using self signed certs in production? Or are you getting an SSL cert from somewhere?

**Comment by upwebdesign** [comment]
@mandersondesign we use self signed certificates.

**Comment by JamesPJ** [comment]
@upwebdesign I've used the `php artisan samlidp:cert` command to create the certficate. But I'm getting error saying `Invalid PEM encoded certificate X509Certificate`. What maybe the issue?. I'm really lost.

**Comment by upwebdesign** [comment]
@JamesPJ Is the certificate created?

**Comment by JamesPJ** [comment]
Yes certificate is created under `storage/samlidp` using the default names as I haven't changed it.
And if I `dd` it in `loadPem` function of `lightsaml` it is printing the below certificate.

`-----BEGIN CERTIFICATE----- MIIEOTCCAyGgAwIBAgIUTlkulBdeoxg21ZvmyZRAIrmQkNQwDQYJKoZIhvcNAQEL BQAwgasxCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcM CUJlbmdhbHVydTEpMCcGA1UECgwgU3ByaW5rbGVXYXkgVGVjaG5vbG9naWVzIFB2 dCBMdGQxEjAQBgNVBAsMCUVkdWNhdGlvbjEQMA4GA1UEAwwHTWFuYWdlcjEjMCEG CSqGSIb3DQEJARYUaW5mb0BzcHJpbmtsZXdheS5jb20wHhcNMjAwNjA0MDcyMzEx WhcNNDAwNTMwMDcyMzExWjCBqzELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUthcm5h dGFrYTESMBAGA1UEBwwJQmVuZ2FsdXJ1MSkwJwYDVQQKDCBTcHJpbmtsZVdheSBU ZWNobm9sb2dpZXMgUHZ0IEx0ZDESMBAGA1UECwwJRWR1Y2F0aW9uMRAwDgYDVQQD DAdNYW5hZ2VyMSMwIQYJKoZIhvcNAQkBFhRpbmZvQHNwcmlua2xld2F5LmNvbTCC ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMjFU3qLEu2SiR+YkuXMVSwo aZwZ6IyZ863dRyzZlBm/JKZWFgbbmQ7tfpL97XcKNozt0VMHwhMdP/xeebrV+xy4 OxStAvTBTtD/hmIQvyfqdi+r0NOBCFKrDzTJgvT3siGE+ZNJot4263d3X6sPP7gX xcFv7yxwbMvk1gZCl/UAE4x0uA43aoYtgwUJczx55/or9brxpPHwDfZYdAkoKfkE k7opvB/ULUQ+XTQjvFwFykcUqQc5SzgnNNWDx62J1lSQ1eMh+1OtjfqnU598QnBB ddHhaPk5rJCzFSQOFaozisNWLxa/mnanIxgEIRXKCRvEOnDWiZNTAahcCvkHwHEC AwEAAaNTMFEwHQYDVR0OBBYEFNsmAW0yH+b8+SXz/HRtFeFwaCsmMB8GA1UdIwQY MBaAFNsmAW0yH+b8+SXz/HRtFeFwaCsmMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI hvcNAQELBQADggEBAIO3+pCmrT0NA8UBWfWN47q9o2Lj/ybGNa8EdIwnUmd+6amm FTBRYELLiUvi4Qm+h4rPtglvdo9/d81wmeru2SKAgIXV0tuU2XIrRzVXZpljV+1N RQGFEcE/VaOrKMQ7u9bVU2FHQwmIlCXIDQaTSPtlrLylIhJwVF4ElXE2NFQNYiL/ yunyW5fhFk6oSV4PQQ/DkTfJNU8c42ZT5iUg2dtRFQXsZ6KADZI60AVandmdKQRO 7wUJjhUf5ZLBbuK1lk5o3ibrfEeiZ17yA4BTadFlCmteNMTPESEcqasC4GiiAdx4 A583kT+Ua3/9pQguDMTwlksEa5fLIppG1VqqEVo= -----END CERTIFICATE-----`

**Comment by upwebdesign** [comment]
@JamesPJ Im not sure what to say except that maybe it’s on the service provider side that is causing issues.

**Comment by JamesPJ** [comment]
@upwebdesign I'm getting the error on `$this->certificate = (new X509Certificate)->loadPem(Storage::disk('samlidp')->get('cert.pem'));` 

However, It maybe related to server configuration as well.

Do you have any recommendation for the server configuration?. My server is running `Debian 10 OS` and `PHP 7.4.6`
