### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by markusnissl** [codegreencreative/laravel-samlidp#20]
Hi,
is there support for Laravel 6.0 planned?

The currently used Version:
```  
"illuminate/support": "^5.6",
"illuminate/routing": "^5.6",
```    
are only allowing up to laravel 5.8

Thanks

**Comment by upwebdesign** [comment]
@markusnissl There is currently a pull request open #19 that addresses this issue. At this point, I am not comfortable enough to release 6.0 support by simply updating the composer.json file. Once it has been tested, a new release will be created.

**Comment by alexander-rieder** [comment]
any news on this?

**Comment by upwebdesign** [comment]
@alexander-rieder no, not really. However, I would like to get Laravel 6 supported. Currently I don't have a project that uses Laravel 6 nor do I have the time to test this at the moment.

**Comment by upwebdesign** [comment]
@alexander-rieder @markusnissl I have made a new release with major version 2. This contains Laravel 6.0 support. I have tested this on my local and staging environments for projects that use this package. It appears everything is working fine from my end.
