### ISSUE TITLE
[Question] Handle SSO via register page, forgot password, etc.

### ISSUE THREAD

**Issue by wdarking** [codegreencreative/laravel-samlidp#21]
Hello

How would be an approach to authenticate the user (sso) via the register page?

The normal flow is: some user tries to access a protected route on the broker, the broker redirects the user to the sso url (login page, in this case) on the idP, the user logs in, the idP redirects the user back to the broker and everything works perfect.

But sometimes the user will not be registered on the idP, and i would like to allow a user registration page, and after the registration the user should be redirected back to the broker, same as login.

Considering the package implementation, it should work the same as the login page (because of the sso listener on the authenticated event), as long as you keep the `SAMLRequest` and `RelayState` query strings on the url. When the broker redirects to the idP, those parameters exists on the url. But, in the idP, if you click a register button or something like that, the parameters will not pass to the next request, unless you do something.

So managed to save the saml parameters in the session as soon as the user enters the login page, so i can use it to populate the register button links with the query parameters.

Something like this in the LoginController

```
    public function __construct()
    {
        $this->middleware('guest')->except('logout');

        session()->forget(['keepSAMLRequest', 'keepRelayState']);

        if (request()->filled('SAMLRequest') && ! request()->is('saml/logout')) {
            session([
                'keepSAMLRequest' => request('SAMLRequest'),
                'keepRelayState' => request('RelayState'),
            ]);
        }
    }
```

Using this, i can use the register buttons like this:

```
<a href="{{ route('register', ['SAMLRequest' => session('keepSAMLRequest'), 'RelayState' => session('keepRelayState') ]) }}">Register</a>
```

And then the parameters would be in the register page request. I just would have to use the `@samlidp` on the register page.

I think this would work, but i would have to clean the session on the authenticated event, and there is already a listener on this event that aborts the request, so i would have to make sure my listener runs before the Sso listener, and i think this starts to be complicated.

I also think messing with session is kinda bad in this case. And it is kinda weird that i would have manually insert the parameters each register button url (same for forgot password, etc).

Anyway, How would be an approach to authenticate the user (sso) via the register, password recovery, etc? Did any of you manage to achieve something like this?

There is a clean/correct way to do this?

**Comment by upwebdesign** [comment]
@wdarking I would not attempt to carry the SAML request through the registration process. I would "remember" where they are coming from, then after registration (assuming they are automatically logged in) initiate SSO from the service provider which will then set the SAML protocol into motion.
