### ISSUE TITLE
Update requirements to Laravel 7

### ISSUE THREAD

**Issue by ellisonpatterson** [codegreencreative/laravel-samlidp#23]
Can the composer.json file be updated for the newest release of Laravel?

Thank you!

**Comment by upwebdesign** [comment]
@ellisonpatterson yes, I will make sure composer.json is updated today.

**Comment by upwebdesign** [comment]
@ellisonpatterson just a quick update, this is more involved than originally thought. We are not going to be able to make this L7.0 compatible by simply updating the composer.json file. I will keep you posted.

**Comment by ellisonpatterson** [comment]
> 
> 
> @ellisonpatterson just a quick update, this is more involved than originally thought. We are not going to be able to make this L7.0 compatible by simply updating the composer.json file. I will keep you posted.

Looks like it's lightsaml but a fork seems to have updated the dependencies for Laravel to be able to include it.
https://github.com/NETFORMIC-GmbH/lightSAML/commit/979ab9e983b9f0ef8f9de565c4555cbc14f5edc2
I don't know if the lightsaml dev would include it.

**Comment by upwebdesign** [comment]
@ellisonpatterson Im not sure I am comfortable in using a fork of lightsaml.

**Comment by ellisonpatterson** [comment]
> @ellisonpatterson Im not sure I am comfortable in using a fork of lightsaml.
Absolutely, I'm just looking to see what can be done at least in a local dev environment for the meantime, just posting that fork which pushed the symphony version to 5.

**Comment by upwebdesign** [comment]
@ellisonpatterson That was the proposed solution for a little while, I may consider doing just that if lightsaml does not update their dependencies.

**Comment by pankaj-ag** [comment]
@upwebdesign Just wanted to check with you if is there any plan to change the composer.json?

**Comment by upwebdesign** [comment]
@pankaj-ag All my projects that use laravel-samlidp are in L6 or L5. Unless I update those projects to L7, I wont be able to take the time to update this package myself. I've inquired about [one of the forks](https://github.com/NETFORMIC-GmbH/lightSAML/commit/979ab9e983b9f0ef8f9de565c4555cbc14f5edc2#commitcomment-38394530) if they could create a pull request for lightSaml with their changes, but we shall see how soon this all gets sorted out.

**Comment by sheixt** [comment]
@ellisonpatterson @pankaj-ag is there any expectation for an update to allow support of L7? Or is there something else we can you in the meantime to act as a workaround to stop blocking the project from being updated?

**Comment by pankaj-ag** [comment]
I am sure what can be done here. 
For now, I just forked the repo and used it in my project. 
https://github.com/ColoredCow/laravel-samlidp

**Comment by sheixt** [comment]
👍  Thanks, @pankaj-ag I'll give that a try and shall report back if it allows the project to upgrade to L7

**Comment by upwebdesign** [comment]
@pankaj-ag @sheixt I just published a 3.0.0 tag with https://github.com/4Labs/lightSAML package. Please keep me informed if you run into any issues with the forked package.

**Comment by sheixt** [comment]
Oh, great @upwebdesign  🎉   Thanks for the quick update! I'm due to circle around to this after the weekend, will return if any issues are present.

**Comment by upwebdesign** [comment]
@sheixt I omitted the v in front of 3.0.0. After editing, it now shows as a tag.

**Comment by sheixt** [comment]
@upwebdesign thanks for confirming. I've been able to run `composer import` with no errors 🥳   I'll report any issues should I find any when testing the application, but I think it's all good now. Thanks for the prompt replies & for the efforts on the package.
