### ISSUE TITLE
Change redirect to my apps instead google service

### ISSUE THREAD

**Issue by mimbar** [codegreencreative/laravel-samlidp#25]
Hey i'm using this as my laravel as idp and google as sp.
after i request to https://mail.google.com/a/domain.com it redirected to my apps. after login, it keep redirect to gmail service.

any solution to make the redirection pointed to my apps instead google service?
thanks

**Comment by upwebdesign** [comment]
@mimbar The way you describe how it is behaving, is exactly how it should behave. You are attempting to go to mail.google.com and not logged in. You are authenticating using your idp. Once authenticated its supposed to go back to mail.google.com as that is the service you are trying to access.
