### ISSUE TITLE
Unable to read PEM, but only on certain requests

### ISSUE THREAD

**Issue by mikemike** [codegreencreative/laravel-samlidp#28]
I'm getting the following error when a SP attempts to log in:

`Invalid PEM encoded certificate`

It's coming from vendor\forlabs\lightsaml\src\LightSaml\Credential\X509Certificate.php:82.

I've edited that file directly and added some debug lines (`\Log::debug('PEM:'); \Log::debug($data)`).  I can see this function being called twice when a user is attempting to log in.  The second time the file is empty, which results in the error. 

This is being called from vendor\codegreencreative\laravel-samlidp\src\Jobs\SamlSso.php:124.  If I set `samlidp.encrypt_assertion` to false I get around it, but my SP fails with `invalidFederatedIdentityActionMessage` - I think they need me to be encrypting.

Any idea?  I saw the other issue with a similar problem where the suggested fix is to downgrade to PHP 7.3.  I tried that, but same problem, but I didn't really expect that to work as the PEM file *CAN* be read, it's just empty on the second attempt.

**Comment by upwebdesign** [comment]
@mikemike There is a lot that goes into debugging something like this. I have a feeling it may be a configuration issue as I have not had this issue myself. I don't think it has anything to do with the SP. I do know that I recently updated this package to allow for L7 using a fork off of lightsaml. Its possible that fork has an issue. I will be working on some SAML stuff for a client soon. I will keep this issue open and in mind when I start working on it.

**Comment by mikemike** [comment]
I'd really appreciate that, thanks.  In essence the bug is that the PEM file is loaded twice, but the second time it's empty.  I guess I can try and deep dive into the relevant packages and see if I can work it out.

**Comment by upwebdesign** [comment]
@mikemike Yes, please do because I have tested this on my end once before without issues.

**Comment by mikemike** [comment]
Hi @upwebdesign 

I've spent a bit of time today digging around and got the SP to disable assertion encryption and message validation so I'm able to get around the issue I was having with the PEM.  I suspect it was a red-herring.

My SP is using KeyCloak, as I mentioned.  KeyCloak is returning `invalidFederatedIdentityActionMessage`.  Looking at the code for KeyCloak this is caused by the response being null (I think): https://github.com/keycloak/keycloak/blob/e22fdabc0287dcc4ae46cefc685f5f8f9786c799/services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java#L519

Is there any reason you could think of that this could be?  SAML seems to be really complex for something fairly straightforward, so I find I'm going down a rabbit hole, often in the wrong direction.  I've shared my config below in case it sheds any light:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | SAML idP configuration file
    |--------------------------------------------------------------------------
    |
    | Use this file to configure the service providers you want to use.
    |
     */
    // Outputs data to your laravel.log file for debugging
    'debug' => true,
    // Define the email address field name in the users table
    'email_field' => 'email',
    // The URI to your login page
    'login_uri' => 'login',
    // Log out of the IdP after SLO
    'logout_after_slo' => env('LOGOUT_AFTER_SLO', false),
    // The URI to the saml metadata file, this describes your idP
    'issuer_uri' => 'saml/metadata',
    // Name of the certificate PEM file
    'certname' => 'cert.pem',
    // Name of the certificate key PEM file
    'keyname' => 'key.pem',
    // Encrypt requests and reponses
    'encrypt_assertion' => false,
    // Make sure messages are signed
    'messages_signed' => false,
    // list of all service providers
    'sp' => [
        // Base64 encoded ACS URL
        // 'aHR0cHM6Ly9teWZhY2Vib29rd29ya3BsYWNlLmZhY2Vib29rLmNvbS93b3JrL3NhbWwucGhw' => [
        //     // Your destination is the ACS URL of the Service Provider
        //     'destination' => 'https://myfacebookworkplace.facebook.com/work/saml.php',
        //     'logout' => 'https://myfacebookworkplace.facebook.com/work/sls.php',
        //     'certificate' => '',
        //     'query_params' => false
        // ]
        'aHR0cHM6Ly9rZXljbG9hay1lbWVh**truncated**W9zby9icm9rZXIvc2FtbC9lbmRwb2ludA==' => [
            'destination' => 'https://keycloak-**truncated**.com/auth/realms/**truncated**/broker/saml/endpoint',
            'logout' => 'https://keycloak-**truncated**.com/auth/realms/**truncated**/broker/saml/logout',
            //'query_params' => true
        ],
    ],

    // If you need to redirect after SLO depending on SLO initiator
    // key is beginning of HTTP_REFERER value from SERVER, value is redirect path
    'sp_slo_redirects' => [
        // 'https://example.com' => 'https://example.com',
    ]
];
```

I created the cert on the server using the command line tool.  Also made the config entry using the tool.

**Comment by upwebdesign** [comment]
@mikemike what version of this package are you using?

**Comment by mikemike** [comment]
Hey @upwebdesign .  I'm on v3.0.0.  I actually think the error was on KeyCloak's side with this, it has some really poor error reporting, and I ended up digging through a load of KeyCloak's java code to work out what was going on.  Our SP (we don't manage it) ended up fixing a few things, and this error seemed to be a blanket error which is nothing to do with the signing of messages - it actually ended up being a mis-matched destination URL.  

Setting `query_params` to `false` was all I needed to do on my end to get things working, but it took a lot of back and forth with the SP to get there.  Still not 100% there as logout and some assertions aren't right, but I think they're also with the SP.  Great package though, been a great help.

**Comment by upwebdesign** [comment]
@mikemike Wow! Happy to hear you are making progress. SAML is quite the mind cruncher at times. There are a lot of variables.

**Comment by isarphilipp** [comment]
Hi guys, I am reopening the issue because I ran into the same situation as you mentioned above.

The solution @mikemike propose works in a way, because it tries to avoid using signing/encrypting in the first place.

While debugging it, i found that `$this->certificate` and `$this->sp_certificate` are indeed not set correctly, and sometimes it's assumed to hold the name of the certfile and in other occasions the content. I'm filing a PR to fix it.
