### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by CreepPork** [codegreencreative/laravel-samlidp#29]

**Comment by upwebdesign** [comment]
@CreepPork is there anything specific you are seeing as to why you have created this issue? Currently I do not have any L8 projects.

**Comment by CreepPork** [comment]
The project's dependencies need to be updated to the latest version - `illuminate/support`. Otherwise, composer fails to install this package.

**Comment by CreepPork** [comment]
L8 also came out today, so it just hit the stable version.

**Comment by upwebdesign** [comment]
@CreepPork Ive updated this package for dev-master to have L8 support. Since I do not have any projects that use L8, I wont be releasing a new version until someone has tested to make sure this works in L8.

**Comment by CreepPork** [comment]
Tested it yesterday and works fine. There's one issue if you have a service provider that it can't find, see #31.

**Comment by upwebdesign** [comment]
@CreepPork I addressed #31 with 2600dbd, but its only in master at the moment.
