### ISSUE TITLE
Internal Server Error When SP is invalid

### ISSUE THREAD

**Issue by tflori** [codegreencreative/laravel-samlidp#31]
I get an exception because `Str::finish` expects a string but gets an `UrlGenerator`. I haven't defined any SP on my local machine and the call `url($destination)` at `/src/Jobs/SamlSso.php#L167` returns the `UrlGenerator`.

Of course as we don't have anything defined in `config.sp.*`... Shouldn't we throw as soon as he is redirected to the login page with an invalid SP?

Versions:
codegreencreative/laravel-samlidp     v2.0.5
laravel/framework                     v6.18.2

**Comment by upwebdesign** [comment]
@tflori 2600dbd5c08dd792a3fafedcab734b3b5d12f964 does this work?

**Comment by tflori** [comment]
yes and no. I mean yes, now I get a slightly more accurate error message: `'%s does not have a destination set in config file.'`. But the real error is: the service provider is invalid - or even more correct: the assertion consumer service url is unknown.

maybe something like that: 
```php
$serviceProvider = $this->getServiceProvider($this->authn_request);
if (!config(sprintf('samlidp.sp.%s', $serviceProvider))) {
    throw new \InvalidArgumentException(sprintf(
        'Invalid or unknown service provider'
    ));
}

$destination = config(sprintf(
    'samlidp.sp.%s.destination',
    $serviceProvider
));
```

**Comment by tflori** [comment]
another question: as I realized that the service provider key is the base64 encoded version of the destination - why to store it two times? I mean it does not increase the security and we could have less mistakes  when the destination would just be the key (for example stripping equal signs `=` from the base64 encoded string). Or just use the destination  he provided, or decode the key.

I'm just wondering for what the conversion is. At the end it is a url to the assertion consumer regardless of the encoding.

**Comment by upwebdesign** [comment]
@tflori base64 encoding the destination URL has to do with config array keys. There were characters the config parser did not like.

**Comment by tflori** [comment]
Ok, the key has to be base64 encoded. Why to have the destination a second time in the config?

And the error message? Not the destination is missing the service provider is invalid.
