### ISSUE TITLE
Usage of not existing controller

### ISSUE THREAD

**Issue by tflori** [codegreencreative/laravel-samlidp#32]
Both controllers (`CodeGreenCreative\SamlIdp\Http\Controllers\LogoutController` and `CodeGreenCreative\SamlIdp\Http\Controllers\MetadataController`) are extending `App\Http\Controllers\Controller`. This class not necessarily exists. For example we renamed our namespace.

Instead the controllers should extend `Illuminate\Routing\Controller` as it is the basic controller.

Also I don't see a reason why they are extending this controller. Maybe there was a reason that I don't see...

**Comment by upwebdesign** [comment]
@tflori I've updated which controller (Illuminate) is used for both controllers in this package.
