### ISSUE TITLE
Trait PerformsSingleSignOn doesn’t rely on samlidp config file to determine the name of the certificate and certificate key file name

### ISSUE THREAD

**Issue by waqleh** [codegreencreative/laravel-samlidp#33]
Issue: `PerformsSingleSignOn` is always trying to get files called `cert.pem` and `key.pem` instead of getting the file names from samlidp config.

How to reproduce: name the certificate file anything other than `cert.pem` or the certificate file key `key.pem`

Error:

```
File not found at path: cert.pem (0)
Illuminate\Contracts\Filesystem\FileNotFoundException thrown with message "cert.pem"
```

Issue in `\CodeGreenCreative\SamlIdp\Traits\PerformsSingleSignOn::init`:
```
$this->certificate = (new X509Certificate)->loadPem(Storage::disk('samlidp')->get('cert.pem'));
$this->private_key = Storage::disk('samlidp')->get('key.pem');
```
Suggested tested solution:
```
$this->certificate = (new X509Certificate)->loadPem(Storage::disk('samlidp')->get(config('samlidp.certname', 'cert.pem')));
$this->private_key = Storage::disk('samlidp')->get(config('samlidp.keyname', 'key.pem'));
```

**Comment by upwebdesign** [comment]
@waqleh Ive added your suggestion to dev-master. Are you able to verify this change works?

**Comment by upwebdesign** [comment]
@waqleh I've added the changes to a new release, v4.1 and v3.2

**Comment by waqleh** [comment]
unfortunately I am using Laravel 6 in my project, can I ask you to do the fix there also (v2.0)?

**Comment by upwebdesign** [comment]
@waqleh v2.0.6 is available.

**Comment by waqleh** [comment]
thanks it works. thanks
