### ISSUE TITLE
Class MetadataController doesn’t rely on samlidp config file to determine the name of the certificate file name

### ISSUE THREAD

**Issue by waqleh** [codegreencreative/laravel-samlidp#34]
Similar issue: https://github.com/codegreencreative/laravel-samlidp/issues/33

Issue: `MetadataController` is always trying to get files called `cert.pem` instead of getting the file names from samlidp config.

How to reproduce: name the certificate file anything other than `cert.pem`

Error:

```
File not found at path: cert.pem (0)
Illuminate\Contracts\Filesystem\FileNotFoundException thrown with message "cert.pem"
```

Issue in `\CodeGreenCreative\SamlIdp\Http\Controllers\MetadataController::index`:
```
$cert = Storage::disk('samlidp')->get('cert.pem');
```
Suggested tested solution:
```
$cert = Storage::disk('samlidp')->get(config('samlidp.certname', 'cert.pem'));
```

**Comment by waqleh** [comment]
Can I ask you to apply the fix starting from v2.0 and so on?

**Comment by upwebdesign** [comment]
@waqleh just to confirm, this was added to v2.0.

**Comment by waqleh** [comment]
@upwebdesign are you sure, i dont see it unfortunately: https://github.com/codegreencreative/laravel-samlidp/blob/2.0/src/Http/Controllers/MetadataController.php

**Comment by waqleh** [comment]
after updating from version ^2.0 to version ^3.0 this issue is back! @upwebdesign can you apply this fix to version 3+ also

**Comment by waqleh** [comment]
thanks for adding it to version 3
