### ISSUE TITLE
Single Sign On URL

### ISSUE THREAD

**Issue by morbidCode** [codegreencreative/laravel-samlidp#35]
Hi all. I have setup my service providers successfully. But unfortunately I can't find what is the SSO url of this library. I have added the saml directive in the login page. But how should an SP initiate going to the IDP (this lib)? That is, what is the SSO url to initiate the authentication process?

Thanks for your work.

**Comment by upwebdesign** [comment]
@morbidCode its your login route.

**Comment by morbidCode** [comment]
@upwebdesign Thanks. However, after loging in I got the following error: Class 'CodeGreenCreative\SamlIdp\Jobs\DestinationMissingException' not found. What is this error?

**Comment by morbidCode** [comment]
Thanks!
