### ISSUE TITLE
V 2.0: Class MetadataController doesn’t rely on samlidp config file to determine the name of the certificate file name

### ISSUE THREAD

**Issue by waqleh** [codegreencreative/laravel-samlidp#40]
issue was fixed here: https://github.com/codegreencreative/laravel-samlidp/issues/34 on master, @upwebdesign can I ask you to please apply the fix to  v2.0 also

https://github.com/codegreencreative/laravel-samlidp/blob/2.0/src/Http/Controllers/MetadataController.php

https://github.com/codegreencreative/laravel-samlidp/blob/650cf3072dbe5178100ab63dcaa41f5455ca24d4/src/Http/Controllers/MetadataController.php#L22

**Comment by upwebdesign** [comment]
@waqleh Ive applied this update to versions 5, 2 and 1.
