### ISSUE TITLE
Cant generate certificate

### ISSUE THREAD

**Issue by IbrahimMuhaisen96** [codegreencreative/laravel-samlidp#43]
I am trying to generate certificate using the command given and I'm getting this message

$ php artisan samlidp:cert [--days=7300 --keyname=key.pem --certname=cert.pem]

  No arguments expected for "samlidp:cert" command, got "[--days=7300".

**Comment by rozenlicht** [comment]
The `[]` are used in the documentation probably to indicate they are optional. Please use:
`php artisan samlidp:cert --days=7300 --keyname=key.pem --certname=cert.pem`

**Comment by upwebdesign** [comment]
@IbrahimMuhaisen96 Those are optional arguments, also showing the default values.

**Comment by IbrahimMuhaisen96** [comment]
Even though, it didn't work !

**Comment by IbrahimMuhaisen96** [comment]
Thanks

**Comment by IbrahimMuhaisen96** [comment]
I did it manually by creating certificates and move them to storage_path

but I'm still getting this error message (openssl_sign(): supplied key param cannot be coerced into a private key) when SP is trying to login

**Comment by TomTangXD** [comment]
Hi @IbrahimMuhaisen96 , did you still get this issue: (openssl_sign(): supplied key param cannot be coerced into a private key) when SP is trying to login? How did you fix it?
