### ISSUE TITLE
Error when accessing saml/metadata

### ISSUE THREAD

**Issue by juliardi** [codegreencreative/laravel-samlidp#44]
I got `syntax error, unexpected 'version' (T_STRING)` while accessing `saml/metadata` route. How to fix this ?
Laravel : v8.24.0
Laravel-samlidp : v5.0.1

![image](https://user-images.githubusercontent.com/4223302/107935398-eb279100-6fb3-11eb-88c6-4598c3b340c9.png)

**Comment by upwebdesign** [comment]
@juliardi I guessing you should turn off php short tags.

**Comment by juliardi** [comment]
@upwebdesign You are right, after disabling php short tags, it worked. Thanks for your response.
