### ISSUE TITLE
Does it support registration as well or should I find any workaround ?

### ISSUE THREAD

**Issue by IbrahimMuhaisen96** [codegreencreative/laravel-samlidp#46]
Should I do some workaround like sending POST request to SP's to register user or is there any option in configuration that support that ?

**Comment by upwebdesign** [comment]
@IbrahimMuhaisen96 Im not really sure what you mean by registration.

**Comment by IbrahimMuhaisen96** [comment]
@upwebdesign User Creation

**Comment by upwebdesign** [comment]
@IbrahimMuhaisen96 I think I will leave it up to the developer to create user accounts. For example, we use user records for authentication only. Some use it as a model to contain much more information about the user. Some may not want to create a user (such as myself) when a new user comes from an SP. So, It is up to you to create the user. We send 
```
->addAttribute(new Attribute(ClaimTypes::PPID, auth()->user()->account->uuid))
->addAttribute(new Attribute(ClaimTypes::EMAIL_ADDRESS, auth()->user()->email));
```
using the SAML Assertion listener so the SP has a uniquely identifiable ID for the user that was created OR just logged in along with the email address.

**Comment by IbrahimMuhaisen96** [comment]
@upwebdesign Thank you for your help, much appreciated
