### ISSUE TITLE
@samlidp

### ISSUE THREAD

**Issue by blorange2** [codegreencreative/laravel-samlidp#49]
I have followed all of the setup instructions for this package and that all makes sense.

My question is around the use of **@samlidp.** inside my login blade.

I placed it just under @csrf in my blade file but when I inspect the HTML I do not see the output I expect, which I'm assuming should be identical to:  https://github.com/codegreencreative/laravel-samlidp/blob/master/resources/views/components/input.blade.php

However, nothing is rendered.

**Comment by upwebdesign** [comment]
@blorange2, sounds like the service provider is not being loaded... what version of Laravel are you using?

**Comment by blorange2** [comment]
@upwebdesign my Laravel version is 6.2, so I installed the version relating to Laravel 6.

**Comment by upwebdesign** [comment]
@blorange2 Im going to close this issue. If something comes up, please reopen or create a new issue.
