### ISSUE TITLE
How do I create an assertion and POST the data to a predefined URL  

### ISSUE THREAD

**Issue by sebabal** [codegreencreative/laravel-samlidp#5]
Hi, basically I need to POST a SAML assertion to a predefined URL that I was given, in order for the users of my app to login automatically to the SP, I have already followed the readme and already done the configuration setup but I am not sure how can I create the assertion in order to make a post.

Cheers.

**Comment by upwebdesign** [comment]
@sebabal It's simple, you don't. The package does that for you. The SP has an initiating URL. If the user is not logged in, they are redirected back to the IdP (login) with a SAMLRequest. The login will recognize the request and generate the assertion and POST it back to the SP.

**Comment by sebabal** [comment]
@upwebdesign thanks for the response yeah looking at the code I realized that was the case. One quick question I am sorry if this is totally unrelated but how does this SAMLRequest look like, it seems is gziped and base64encoded, do you have an example of this request. I am trying to generate one.

**Comment by upwebdesign** [comment]
@sebabal The only way I know of is to create a SP locally that implements SAML as well.
