### ISSUE TITLE
Relay back to service provider after authentication

### ISSUE THREAD

**Issue by zanderwar** [codegreencreative/laravel-samlidp#50]
Hello

Not sure if I'm missing something or if it's attended, but after logging in via SSO i'm not redirected back to the SP initiator and instead i'm just taken to the home page of the IdP.

I'm using /login as the IdP ACS URL.

Thanks

**Comment by upwebdesign** [comment]
@zanderwar that is strange behavior. Off the top of my head, Im not sure what could be happening.

**Comment by upwebdesign** [comment]
@zanderwar were you able to solve the issue on your own? Im closing this issue for now.

**Comment by Sunappnio** [comment]
check you have added the blade directive "@samlidp" in you view, and the directive is realling working.

 In my case, after i moved the project location, i have to run "php artisan view:clear" to make it work again
