### ISSUE TITLE
[QUESTION] Are nested attributes possible?

### ISSUE THREAD

**Issue by seanstickle** [codegreencreative/laravel-samlidp#55]
I have a service provider (Twilio Flex) that needs nested attributes for certain functionality:

`"routing": { "skills": [ "Spanish", "Latin" ] }`

Is it possible to set nested attributes in `SamlAssertionAttributes.php`?

I tried the naive way:

```
$skills = new Attribute('skills', ['Spanish', 'Latin']);

$event->attribute_statement
      ->addAttribute(new Attribute(ClaimTypes::PPID, $user->id))
      ->addAttribute(new Attribute('routing', $skills));
```

...but that didn't work.

**Comment by upwebdesign** [comment]
@seanstickle can you try sending as a JSON encoded string?

**Comment by seanstickle** [comment]
Good idea. Based on your suggestion, I tried this:

```
$skills = json_encode(['skills' => ['English', 'Catalan']]);

$event->attribute_statement
      ->addAttribute(new Attribute(ClaimTypes::PPID, $user->id))
      ->addAttribute(new Attribute('routing', $skills));
```

But the JSON encoded content seems to get escaped when sent to the service provider:

```
"routing":"{\"skills\":[\"English\",\"Catalan\"]}"
```

**Comment by upwebdesign** [comment]
@seanstickle hmm, Im not sure at this point.

**Comment by upwebdesign** [comment]
@seanstickle could you try something like this?
```
->addAttribute(new Attribute('skills.array', 'Spanish, Latin'));
```

**Comment by seanstickle** [comment]
That _does_ work for flat skills, but doesn't achieve the nested `routing: { skills: [ 'Spanish', 'Latin' ] }` attribute.

**Comment by seanstickle** [comment]
Aha! This works:

```
$skills = json_encode(['skills' => ['Spanish', 'Latin']]);

$event->attribute_statement
      ->addAttribute(new Attribute(ClaimTypes::PPID, $user->id))
      ->addAttribute(new Attribute('routing.json', $skills));
```

You pointed me in the exact write direction, @upwebdesign. Thank you!

**Comment by upwebdesign** [comment]
@seanstickle happy to hear you figured it out!
