### ISSUE TITLE
certificates cleanup while generating metadata.xml 

### ISSUE THREAD

**Issue by robverhoef** [codegreencreative/laravel-samlidp#6]
When uploading the metadata 'as is' some service providers, like https://samltest.id will trip over the 
> -----BEGIN CERTIFICATE-----

and 
> -----END CERTIFICATE-----

lines. 
I think these lines should be stripped when generating the certificates or -probably better- before putting out the metadata.xml. 
The newlines may be removed from the certificate as well.

This is a promising project by the way!

**Comment by upwebdesign** [comment]
@robverhoef I will keep this issue open for now. Maybe someone can open a pull request with the suggested changes. Thanks for pointing this out!

**Comment by upwebdesign** [comment]
This has been resolved with pull request #7
