### ISSUE TITLE
[QUESTION]  Invalid PEM encoded certificate

### ISSUE THREAD

**Issue by awshowo** [codegreencreative/laravel-samlidp#62]
Hello,
i am new to sso and I try to authorize https://sptest.iamshowcase.com.
But I always run into "Invalid PEM encoded certificate".
I created an SP with "php artisan samlidp:sp"
"
    'sp' => [
        'aHR0cHM6Ly9zcHRlc3QuaWFtc2hvd2Nhc2UuY29tL2Fjcw==' => [
            'destination' => 'https://sptest.iamshowcase.com/acs',
            'logout' => '',
            //'certificate' => '',
            //'query_params' => false
        ]
"
After that I uploaded my metadata file to sptest.iamshowcase.com.
But when I try now to login over "https://sptest.iamshowcase.com/ixs?idp=ee55f286fbd8efe77e2033ad817fd91e04de4e01"
I got every time after pushing the Login button the "Invalid PEM encoded certificate" error.

I tried it with Laravel 6 and 8 an samlidp 2 and 5

can someone help me?

At the end I will work with sli.do as SP

THX for Help
Nils

**Comment by Muneeb-Ahmed-Khan** [comment]
Hello, I am having the same issue,
How did you solve it ?

**Comment by awshowo** [comment]
Hello,
I don't Solved it.
At the end I used http://www.lightsaml.com/LightSAML-Core/
and no Laravel

**Comment by Muneeb-Ahmed-Khan** [comment]
I just solved it 10 minutes ago. My idP is working well now.
If you want help, I can help you out with what i did.

**Comment by upwebdesign** [comment]
@Muneeb-Ahmed-Khan I would definitely be interested in what you did.

**Comment by Muneeb-Ahmed-Khan** [comment]
It's not much of a technical but i will explain what solved the problem for me.
My Laravel Application is acting as IdP and FreshDesk is working as SP here.

FreshDesk just want Signed Response, It does not need Signed Assertion.

I simply disabled Signed Assertion by setting  `'encrypt_assertion' => false` Rest of the stuff is default config.

Take a look at the screenshot I attached.

![image](https://user-images.githubusercontent.com/49415395/128912681-f32d23b3-0cd6-4f85-a3fb-c6a3e231ddb0.png)

**Comment by upwebdesign** [comment]
@Muneeb-Ahmed-Khan welp, that was a simple solution. Glad you got it working!

**Comment by sprklinginfo** [comment]
@upwebdesign, I am having the same error when trying to use 'https://github.com/aacotroneo/laravel-saml2' on another laravel site that is acting as SP. If I follow @Muneeb-Ahmed-Khan solution to disable encryption on IdP, the error is gone.  But it is a good practice? I am concerned it might weaken the security of IdP. Is there a way to actually fix the error while still enabling encryption?

BTW, when using the command to generate a new SP, I can see there is a 'certificate' key in the sp array() (default). does this key mean the same 'cert.pem' file? or the certificate should come from the SP? In addition, on the SP site,  its config also asks for 'x509cert' and 'privateKey' which I don't know if they have anything to do with the IdP site.

**Comment by mankowitz** [comment]
I've run into this problem as well. The problem is that in order to encrypt assertions, you need to have the SP's X509 cert. This information is pulled from /config/samlidp.php

In samlSso.php, 
```
        // Encrypt the assertion
        if (config('samlidp.encrypt_assertion')) {
            $this->setSpCertificate();
 
            $encryptedAssertion = new EncryptedAssertionWriter();
            $encryptedAssertion->encrypt($assertion, KeyHelper::createPublicKey(
                (new X509Certificate)->loadPem($this->sp_certificate)
            ));
            $this->response->addEncryptedAssertion($encryptedAssertion);
        } else {
            $this->response->addAssertion($assertion);
        }
```

So, if you have `encrypt_assertion` set to `true` but don't have a `certificate` defined in the config file, it will fail. I would suggest this modification
```
        // Encrypt the assertion
        $this->setSpCertificate();
        if (config('samlidp.encrypt_assertion') && !empty($this->sp_certificate)) {
            $this->setSpCertificate();
 
            $encryptedAssertion = new EncryptedAssertionWriter();
            $encryptedAssertion->encrypt($assertion, KeyHelper::createPublicKey(
                (new X509Certificate)->loadPem($this->sp_certificate)
            ));
            $this->response->addEncryptedAssertion($encryptedAssertion);
        } else {
            $this->response->addAssertion($assertion);
        }
```

**Comment by upwebdesign** [comment]
@mankowitz so you need the ability to cherrypick the SP's that need the assertion encrypted?

**Comment by mankowitz** [comment]
So, let's say, for example, that you want to test your IdP against multiple SP's (the usual case). I found two publicly available testing SP's, although there may be more.

1. https://samltest.id/
2. https://sptest.iamshowcase.com/

The first one wants encrypted assertions, while the second one doesn't.

**Comment by upwebdesign** [comment]
@mankowitz right, I never had the need for this, but I can see why you may need to have this functionality.

**Comment by mankowitz** [comment]
Out of curiosity, I was not able to connect to https://samltest.id/,  (or zoom, for that matter). Were you able to?

**Comment by KenGuggelmeyer** [comment]
I'm also getting this error message when i'm enabling 'encrypt_assertion' in the samlidp.php config file.

I'm using a self-issued certificate from this package with the default config settings provided. I also issued the certificate in my Service Provider application. Tried to recreate the certificate etc. but the error persists.

I know that requests are also encrypted on the Transport Level when using SSL but this should work because it will assure that the requests remains encrypted through the entire http request.

Any advice how to troubleshoot this?

**Comment by mankowitz** [comment]
Did you have the same problem as I did? Do you have the X509 cert defined by the recipient?

**Comment by KenGuggelmeyer** [comment]
I have created a SP with the following package: https://github.com/aacotroneo/laravel-saml2. In that package I have included the idp certificate generated with this package in the config section of the defined idp. It was my understanding that this should have been enough to use the encrypt assertion in the idp application.
