### ISSUE TITLE
[QUESTION] It's possible to initiate a Single Log Out for different user that is not the current one

### ISSUE THREAD

**Issue by JulioWar** [codegreencreative/laravel-samlidp#65]
I have this use case I want to implement. I need to implement a feature to close all session for specific user as administrator. I am new to  SAML implementation so I don't know if this is something that SAML support or need to be handled apart.

Do you think is something that can be done with this library ?

thanks in advance for the help or the guidence that you can give me.

**Comment by upwebdesign** [comment]
@JulioWar I would suggest that this be handled apart from SAML. The functionality you are requiring should be handled by the application as it is an application specific requirement.

**Comment by JulioWar** [comment]
Hi @upwebdesign,

I already implemented that functionality, but I just wanted to make sure I was not missing something. 

Thanks for take the time to respond
