### ISSUE TITLE
[QUESTION] login / redirect 

### ISSUE THREAD

**Issue by adelmazza** [codegreencreative/laravel-samlidp#66]
Hi,

I've installed and configured this library on a laravel project with Fortify as authentication backend.
I followed the readme for installation and configuration but when I open the /login url nothing happens: the default login with email/password is shown and working and in the html source there is no output for @samlidp
Can someone help me?
Thanks a lot!

**Comment by upwebdesign** [comment]
@adelmazza there could be a number of reasons why `@samlidp` would not spit out the required HTML. Please provide more context on what you are trying to do and what version of Laravel are you using?

**Comment by adelmazza** [comment]
> @adelmazza there could be a number of reasons why `@samlidp` would not spit out the required HTML. Please provide more context on what you are trying to do and what version of Laravel are you using?

Thanks for your reply!
Laravel. v8.36.1
Fortify v1.7.9

Below the boot method of the Fortify Service Provider:

`public function boot()
    {
        // bypasso login default di fortify
        Fortify::authenticateUsing(function (Request $request) {
            $user = User::where('email', $request->email)
                ->where('password', $request->password)
                ->first();

            return $user;
        });

        Fortify::loginView(function () {
            return view('auth.login');
        });

        Fortify::createUsersUsing(CreateNewUser::class);
        Fortify::updateUserProfileInformationUsing(UpdateUserProfileInformation::class);
        Fortify::updateUserPasswordsUsing(UpdateUserPassword::class);
        Fortify::resetUserPasswordsUsing(ResetUserPassword::class);

        RateLimiter::for('login', function (Request $request) {
            return Limit::perMinute(5)->by($request->email.$request->ip());
        });

        RateLimiter::for('two-factor', function (Request $request) {
            return Limit::perMinute(5)->by($request->session()->get('login.id'));
        });
    }`

and below a snipped of the blade template

`<form action="{{route('login')}}" method="post">
                                        @csrf
                                        @samlidp

                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="text" class="form-control" id="email" name="email" value="{{old('email')}}" placeholder="">
                                        </div>

                                        <div class="form-group">
                                            <label for="password">Password</label>
                                            <input type="password" class="form-control" id="password" name="password" placeholder="">
                                        </div>`

Thanks a lot for your support

**Comment by upwebdesign** [comment]
@adelmazza is it possible its because @csrf and @samlidp are on the same line?
