### ISSUE TITLE
how to connect to office365

### ISSUE THREAD

**Issue by abublihi** [codegreencreative/laravel-samlidp#68]
Hi there,

In our organization our users have an account in the office365, we wanted to make our SSO to sign in the users in to Office365, but we have face some problems the first one is that the office365 is routing to /login with `POST` method this isn't a big deal, the problem is with the `SAMLRequest` coming form mirosoft which dose not contain `AssertionConsumerServiceURL`.

Normal Saml Request:
```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_ae3a207258e0ebd73a13e8dc231b3cd44680105a"
                    Version="2.0"
                    ProviderName="Display Name"
                    IssueInstant="2021-08-10T07:48:41Z"
                    Destination="http://localhost:8030/login"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="http://localhost:8010/saml/test/acs"
                    >
    <saml:Issuer>http://localhost:8010/saml/test/metadata</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
                        AllowCreate="true"
                        />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

Saml Request from Microsoft:
```xml
<samlp:AuthnRequest ID="_e8039dc5-3744-4b00-b2c8-7b985dea2928"
                    Version="2.0"
                    IssueInstant="2021-08-10T11:48:45.996Z"
                    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">urn:federation:MicrosoftOnline</Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" />
</samlp:AuthnRequest>
```

Any idea to resolve this problem. 

reference: [https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-saml-idp](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-saml-idp)

Thank You.

**Comment by upwebdesign** [comment]
@abublihi I would imagine that there is a setting in Office365 to turn that option on. I dont know anything about Office365 so I am unable to help. Good luck!

**Comment by Priet** [comment]
I'm running into the same problemen connecting with Microsoft 365 Entra SAML (External Identity). 

@abublihi did you ever found a solution?

**Comment by abublihi** [comment]
@Priet I did make our SAML IDP, it's too simple to do.

**Comment by Priet** [comment]
@abublihi Great to hear! Can you elaborate a bit or point me in the right direction? I'd love to make it work with connecting Entra to our own custom SAML IDP.
