### ISSUE TITLE
syntax error, unexpected identifier "version"

### ISSUE THREAD

**Issue by Muneeb-Ahmed-Khan** [codegreencreative/laravel-samlidp#69]
I am using Laravel 8 in production env.
I have nginx as webserver and when my request is made to  `https://domain.tld/saml/metadata` A `500 Server Error` is thrown.
After checking the reason for this at log file. I saw.

![image](https://user-images.githubusercontent.com/49415395/129354829-610f0d95-4b75-4bb8-bdb1-ff66fe835c50.png)

After opening this metadata.blade.php file in my editor 
![image](https://user-images.githubusercontent.com/49415395/129354964-eb01f0bf-5562-4f0c-8f71-b6fb47f4613c.png)

VS Code indicates an error at line 1. But when I close it. VS Code does not show any indication of error.

On my localmachine. Everything works well. Below is the image from my local machine with XAMP Apache.
![image](https://user-images.githubusercontent.com/49415395/129355238-0c5aff94-18ae-4e2a-89b0-4772c4d40677.png)

Did anyone ever experienced this kind of issue with this package, Please let me know how to solve it. 
Thanks in advance.

**Comment by Muneeb-Ahmed-Khan** [comment]
As it is working in local machine but not with production server. I did a test and issued this command
`vi /var/www/html/vendor/codegreencreative/laravel-samlidp/resources/views/metadata.blade.php`
After opening this file in vi editor.

I removed the first line.
![image](https://user-images.githubusercontent.com/49415395/129356247-5988374d-7d46-490b-b983-636a46e07ef8.png)

As you can see that there is no `<?xml version="1.0"?>` at first line. This solves the problem at my production server.

This is just a quick fix but I know this not a permanent solution for my problem. Maybe the problem is with nginx configuartion. I am sending every .php request to php-fpm so it is messing the stuff up. I will perform another test and exclude this `https://domain.tld/saml/metadata` request from nginx php and server it directly as file to see what happens.

**Comment by Muneeb-Ahmed-Khan** [comment]
After going through it again. This is not an nginx configuration fault.

I will drop my conf if someone finds any error in it, Please let me know.
![image](https://user-images.githubusercontent.com/49415395/129359838-f36fb824-88ad-4f6a-8edc-93437206bebe.png)

**Comment by upwebdesign** [comment]
@Muneeb-Ahmed-Khan  If I recall correctly, its a PHP configuration problem. Unfortunately I dont know what the solution is. Maybe it has something to do with short tags. `<?`

**Comment by Muneeb-Ahmed-Khan** [comment]
> @Muneeb-Ahmed-Khan If I recall correctly, its a PHP configuration problem. Unfortunately I dont know what the solution is. Maybe it has something to do with short tags. `<?`

Yes, It is the `<?xml` tag that is creating the problem.
I guess, the php expects `<?php` there but find `xml`. That's why it throws error.

**Comment by upwebdesign** [comment]
@Muneeb-Ahmed-Khan  have you tried turning off short tags in your php.ini?
