### ISSUE TITLE
Question: Are there any laravel packages for SP you can recommend?

### ISSUE THREAD

**Issue by sprklinginfo** [codegreencreative/laravel-samlidp#75]
Thanks for creating the package to turn a Laravel site into an IdP. SSO is a pretty new field to me. Can you recommend any packages to make other sites to be SP? I did some research, most of the places mentioned about https://github.com/aacotroneo/laravel-saml2 or https://github.com/miniOrangeDev/saml-laravel-free. thanks.

**Comment by upwebdesign** [comment]
@sprklinginfo We have implemented these SP packages with laravel-samlidp

https://github.com/aacotroneo/laravel-saml2
https://github.com/onelogin/php-saml

**Comment by sprklinginfo** [comment]
thanks @upwebdesign. I will try them.
