### ISSUE TITLE
Question about Log out of IdP after SLO

### ISSUE THREAD

**Issue by sprklinginfo** [codegreencreative/laravel-samlidp#76]
I've made the login from my SP work. but when the user logs out, it appears logged out on my SP. If I hit the login again, the SP login screen prompts. Good so far. but if I chose the same IdP login link again, it authenticates me right away without redirecting me to the IdP login screen. Feel that the IdP didn't actually log me out. In my IdP's .env file, I do have this line: LOGOUT_AFTER_SLO=true.

But if I close the browser after the first logged out, then visit the SP login and choose IdP login link, it redirects me to the IdP login screen. So to completely logout of the IdP, the user must close the browser otherwise it stays logged in on IdP, is this the right behavior?

If this is expected behavior, are there any ways I can force the user on the SP to enter their email/password on the IdP login screen again without closing the browser?

**Comment by upwebdesign** [comment]
@sprklinginfo that does not sounds like the correct behavior, no. You will need to work on your SAML flow when logging out. The IdP does not log people out of the SP's, the SP's need to log the user out during the SAML logout process.

**Comment by sprklinginfo** [comment]
thanks @upwebdesign , it turns out  I have to make two changes (use aacotroneo/laravel-saml2 package) on the SP site : 

1. I need to set 'singleLogoutService'  to be "https://myidp.com/saml/logout" instead of native laravel '/logout' (while native '/login' is fine for login by adding @samlidp in login blade file). I think the readme file doesn't make it this very clear. Maybe I am pretty new to the whole SAML land so I didn't get this bit at first.
2. In laravel native layout file, the logout link is a form posting to '/logout'. I tried to override built-in logout() in Auth\LoginController, e.g. redirect to 'saml2_logout' route after logging out locally but it didn't work. so I end up updating the blade file to show a link to 'saml2_logout' route if the user is authenticated via the IdP, otherwise shows the native /logout form. Not sure if this is the correct way doing LOL.
