### ISSUE TITLE
How can I add an extra field validation to the Login?

### ISSUE THREAD

**Issue by msslgomez** [codegreencreative/laravel-samlidp#77]
I've tried adding dds and Logs to my regular app/Http/Controllers/LoginController but the changes never are reflected, how would I achieve this? I want to check if `$user->is_active` is true.

**Comment by upwebdesign** [comment]
@msslgomez Im not sure to be honest.

**Comment by sprklinginfo** [comment]
@msslgomez, do you mean this?
```
if (Auth::attempt(['email' => $email, 'password' => $password, 'active' => 1])) {
    // The user is active, not suspended, and exists.
}
```
From the doc: https://laravel.com/docs/8.x/authentication#specifying-additional-conditions
