### ISSUE TITLE
Replace default email address

### ISSUE THREAD

**Issue by mankowitz** [codegreencreative/laravel-samlidp#78]
Is there a way to change the email address provided to the SP? For example, on our SP, the users are all of the form z-user@domain.com, while on our system, they are user@domain.com. From what I can tell, you can always add more attributes, but you can't remove them.

This isn't working:
```
namespace App\Listeners;

use LightSaml\ClaimTypes;
use LightSaml\Model\Assertion\Attribute;
use CodeGreenCreative\SamlIdp\Events\Assertion;

class SamlAssertionAttributes
{
    public function handle(Assertion $event)
    {
        $event->attribute_statement
            ->addAttribute(new Attribute(ClaimTypes::EMAIL_ADDRESS, "z-user@domain.com"));
    }
}
```

**Comment by upwebdesign** [comment]
@mankowitz if you do not want to use an attribute you can ignore it. Most SP's are looking for an email address. If this becomes a problem, we could use yet another config option to exclude the email address attribute. I don't see any harm in adding this check. Would you be able to provide a PR with the code update?

**Comment by mankowitz** [comment]
Actually, there might be a cleaner way to do this. If I make an attribute on the User model called `samlEmail` and then specify that the email field in the config should be `samlEmail` instead of `email`, that should work, right?

```
// /config/samlidp.php
return [

    'email_field' => 'samlEmail',
```

And then, in app\User.php
```
    public function samlEmail()
    {
        return  'z-' . $this->email;
    }
```

**Comment by upwebdesign** [comment]
@mankowitz good idea, let me know if it works!

**Comment by mankowitz** [comment]
It does work.
