### ISSUE TITLE
Question (maybe a bug); what does the ?idp=... parameter in the destination do?

### ISSUE THREAD

**Issue by robverhoef** [codegreencreative/laravel-samlidp#8]
SimpleSaml is rather strict when comparing destinations. The idp query parameter causes an exception when testing locally.

Caused by: Exception: Destination in response doesn't match the current URL. Destination is "http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp?idp=http://localhost", current URL is "http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp".

Commenting the parameter out on https://github.com/codegreencreative/laravel-samlidp/blob/master/src/Jobs/SamlSso.php#L59 seems to fix it.

**Comment by upwebdesign** [comment]
@robverhoef I have not used SimpleSaml to implement a service provider. I have used the IdP parameter for the service provider settings file when describing the IdP. It was more for convenience. I believe I ran into a problem of not knowing who the IdP was from the service provider.

**Comment by zanderwar** [comment]
It may be worth adding the `?idp=` parameter as an SP configuration option? It would solve the issue SimpleSaml users face while still allowing you to provide it for your SP's @upwebdesign

**Comment by mbaxter91288** [comment]
@upwebdesign I've had the same issue as well. Currently setting my destination directly in [https://github.com/codegreencreative/laravel-samlidp/blob/master/src/Jobs/SamlSso.php#146](https://github.com/codegreencreative/laravel-samlidp/blob/master/src/Jobs/SamlSso.php#146). Any help would be appreciated.

**Comment by ellisonpatterson** [comment]
Same issue happening with Google SAML SSO with the destination not matching, so it's something that should be handled accordingly via a config setting.
