### ISSUE TITLE
Redirect after logout misses SAMLResponse query once every two

### ISSUE THREAD

**Issue by izayoi256** [codegreencreative/laravel-samlidp#81]
I'm new to sso, so learning it with this library.

Here is my sp config.
```
    'sp' => [
        'blahblahblah' => [
            'destination' => 'http://localhost:8500/login.php?acs',
            'logout' => 'http://localhost:8500/logout.php?sls',
            'certificate' => '...',
            'query_params' => false,
        ],
```

When I initiate logout first time, `saml.slo` is empty. So `SamlSlo` is correctly dispatched here, and redirect destination includes `SAMLResponse` query.
https://github.com/codegreencreative/laravel-samlidp/blob/81b101e3bead81a80d67644230c64dde99963ce6/src/Http/Controllers/LogoutController.php#L35

I initiate logout again after that, `saml.slo` is not empty. Redirect response is returned here, and the destination is just `http://localhost:8500/logout.php?sls`.
https://github.com/codegreencreative/laravel-samlidp/blob/81b101e3bead81a80d67644230c64dde99963ce6/src/Http/Controllers/LogoutController.php#L47

Is this expected behavior? How do I get redirect response with `SAMLResponse` query every time?

**Comment by izayoi256** [comment]
I solved the question myself. I'm sorry that I misunderstood how LogoutController:index() worked.

**Comment by seismicsix** [comment]
Hi,

i am experiencing the same issue - would you mind sharing what you learnt about the logout process, why it happens and how you resolved it.

Thanks
