### ISSUE TITLE
My logout request for SLO keeps throwing an error saying I should be making an AuthnRequest, not a LogoutRequest

### ISSUE THREAD

**Issue by dominickish** [codegreencreative/laravel-samlidp#83]
SSO works great, every time I try to use SLO though I get this error:

`Expected 'AuthnRequest' xml node and 'urn:oasis:names:tc:SAML:2.0:protocol' namespace but got node 'LogoutRequest' and namespace 'urn:oasis:names:tc:SAML:2.0:protocol'`

The endpoint destination looks right, have you dealt with this error before? I'm having a hard time finding anything on it searching Google.

**Comment by upwebdesign** [comment]
@dominickish I have not run across this issue myself. It almost sounds like the SP is attempting to login not logout.

**Comment by dominickish** [comment]
Here is my logout request, does it look right to you?

```
<samlp:logoutrequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" id="ONELOGIN_65986ec6f7d2210b9044e24ac739e42bef585bfd" version="2.0" issueinstant="2022-02-22T19:22:09Z" destination="https://my-destination-end-point.com">
<saml:issuer format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" namequalifier="http://sp2.simevo.com:8000">http://requestee-entityId.com</saml:issuer>
<saml:nameid format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">my-user-logging-out@email.com</saml:nameid>
<samlp:sessionindex>_3cf97357196ece9e244a9c2cc678565b8cec659ef6</samlp:sessionindex>
</samlp:logoutrequest>
```

**Comment by upwebdesign** [comment]
@dominickish sorry I cannot be more help, but I don't have any experience with OneLogin. Maybe someone that uses this package with OneLogin will be able to chime in.

**Comment by sprise** [comment]
I had this problem today and wanted to drop a little trail in case it helps anyone down the road. AuthnRequest is generated for **Sign In** requests, so if you see this happen, you have perhaps hit the wrong URL. 

In my case I had the _Service Provider_ set up to hit idp.lan/logout instead of idp.lan/**saml**/logout.
