### ISSUE TITLE
composer require codegreencreative/laravel-samlidp not working with laravel 9

### ISSUE THREAD

**Issue by brpassos** [codegreencreative/laravel-samlidp#85]
Problem 1
    - forlabs/lightsaml 2.0.0 requires symfony/http-foundation ~5.0 -> found symfony/http-foundation[v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - codegreencreative/laravel-samlidp v5.1.0 requires forlabs/lightsaml ^2.0 -> satisfiable by forlabs/lightsaml[2.0.0].
    - Root composer.json requires codegreencreative/laravel-samlidp ^5.1 -> satisfiable by codegreencreative/laravel-samlidp[v5.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require codegreencreative/laravel-samlidp:*" to figure out if any version is installable, or "composer require codegreencreative/laravel-samlidp:^2.1" if you know which you need.

**Comment by upwebdesign** [comment]
@brpassos Ive updated dev-master to use lightsaml/lightsaml which supports symphony 6.0. If you are able to get it to work on your end (since I don't have a L9 project yet), I will make a release with this change in it.

**Comment by brpassos** [comment]
@upwebdesign thanks for the quick response. After its change it was possible to install the package. But it's the first time I work on an idp project. So it will take me some time to use it.

**Comment by brpassos** [comment]
@upwebdesign It worked with Laravel 9, but I had to create a logout route with get, as laravel 9 uses post on logout by default.

`Route::get('logout', [AuthenticatedSessionController::class, 'destroy'])
                ->name('logout');`

**Comment by upwebdesign** [comment]
@brpassos when you are feeling comfortable with `dev-master`, please let me know :)

**Comment by brpassos** [comment]
@upwebdesign looks like it's working fine!

**Comment by upwebdesign** [comment]
@brpassos thanks for the feedback, I did release v5.1.1 this morning. Thank you for responding back!
