### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by TomTangXD** [codegreencreative/laravel-samlidp#87]
Hi, I am encountering a CORS error : `Access to XMLHttpRequest at …  (redirected from ’…) from origin ‘...’ has been blocked by CORS policy: Response to preflight request doesn’t pass access control check: No ‘Access-Control-Allow-Origin’ header is present on the requested resource.`

And in the Listeners/SamlLogout.php file, if I change the `abort(redirect('saml/logout'), 200);` to `return redirect('saml/logout');`this issue won't happen, but I don't really want to change it every time if I install or update composer, besides I am not sure if this is going to affect any security stuff. So may I ask if there is any alternative approaches to solve this issue?

Thanks!

**Comment by upwebdesign** [comment]
@TomTangXD what version of Laravel are you using?

**Comment by TomTangXD** [comment]
@upwebdesign 8.32

**Comment by ChadwickLloyd** [comment]
Running into the same issue - has there been any resolution?

**Comment by viet-nguyen-1926** [comment]
@upwebdesign 
I have updated to v5.2.7 but still have this bug.
