### ISSUE TITLE
IssuerID

### ISSUE THREAD

**Issue by tiagodevweb** [codegreencreative/laravel-samlidp#88]
Hello, the SP that I need to integrate asks for an ID called issuerID which would be the domain of the IDP, where do I configure this key?
**getAbstract** documentation:
IssuerID: Unambiguous identification of the Identity Provider (URL or String)

**Comment by upwebdesign** [comment]
@tiagodevweb I am not sure. Base on what you are asking for I can think of two places where the issuerID might be used. First, as part of the metadata XML. Second, as part of the assertion.

Concerning assertions, `$this->issuer = url(config('samlidp.issuer_uri'));` I believe is what you are looking for
