### ISSUE TITLE
metadata error when forced to use short PHP tags

### ISSUE THREAD

**Issue by robverhoef** [codegreencreative/laravel-samlidp#9]
Minor issue; when a host has short_open_tag=1 -I know …very bad practice- and you cannot do anything about it (in php.ini) then calling /saml/metdata will fail because of the opening XML-tag.
As an ugly workaround, replacing the opening tag with 
`<?php echo '<?xml version="1.0"?>'?>`
will work. 
I'm not sure if this should be fixed here. As said, using short tags is a bad practice anyway.

**Comment by upwebdesign** [comment]
@robverhoef I think the correct solution to this is to publish the views into your project and make the necessary changes there for this scenario. You are correct in stating that short tags are a terrible idea and should no longer be used.
