### ISSUE TITLE
Nothing renders with @samlidp on latest laravel (9.11, sail)

### ISSUE THREAD

**Issue by aleksanm** [codegreencreative/laravel-samlidp#92]
I tried with laravel sail, and on login.blade.php added @samlidp, but when started, nothing renders. Trie to clean cache, run dev etc.. Nope.

**Comment by upwebdesign** [comment]
@aleksanm there have been other issues saying @samlidp is not working, like #79. This ticket does not contain enough information to even make guesses as to why it is not working for you. Feel free to add more detail.

**Comment by baskinvolkan** [comment]
same here, did u find any solution?

**Comment by aleksanm** [comment]
Yes. Proper understanding of saml and did the right configuration and it's works..
