### ISSUE TITLE
Getting Metadata XML

### ISSUE THREAD

**Issue by ChadwickLloyd** [codegreencreative/laravel-samlidp#97]
Hi,

Im fairly new to SAML, and laravel - so sorry in advance.

I'm aiming to use a moodle site as a service provider, where a user can login to a laravel web app, then access moodle having been verified.

To set up moodle as a SP, it requires some setup steps (at least with the plugin I have found). One of these steps is to input a metadata xml.

So far I am unable to find a generated Metadata xml file, or find generated xml. 

Is there some way to do this? or any advice?

Cheers.

**Comment by upwebdesign** [comment]
@ChadwickLloyd could you please start a new discussion, what you are describing is not really an issue. I can help you with your question over there.
